[Bug/Refactor] svg 색상 변경 버그 해결 및 리팩토링
Dev-FE-1/idle-intranet-service pull request #33
Opened 2024-06-25 13:54 UTC by devdeun

# 🚀 풀 리퀘스트 제안

Icon 컴포넌트를 추가해 svg 색상 변경 버그를 해결했습니다.
Icon 컴포넌트를 추가하니까 Navbar 컴포넌트가 복잡해져서 Menu 컴포넌트로 분리하는 리팩토링 작업도 같이 진행했어요!

## 📋 작업 내용

- svg 아이콘 제어를 위한 Icon 컴포넌트 추가
- Menu 컴포넌트 분리
   - 메뉴도 네비게이션의 일부라서 따로 폴더를 만들지 않고 Navbar 폴더 안에 추가

## 🔧 변경 사항

- utils 폴더 생성
    - 아이콘 svg html을 export 하기 위한 `icon.js` 파일 추가
    -  상수를 관리할 `constants.js` 파일 추가

## 📸 스크린샷 (선택 사항)

<img width="211" alt="image" src="https://github.com/Dev-FE-1/idle-intranet-service/assets/108856689/4c7e196a-18cb-4fcd-accb-d8eececa9f88">

2024-06-25 14:01 UTC, seoyoonyi approved these changes
svg를 자바스크립트 코드에 정의해서 사용하는걸 보고... 오.... 서버요청까지 안가도 되겠다는 생각을 했답니다... 너무 좋습니다....굿.....

2024-06-25 14:15 UTC, seoyoonyi requested changes
아이콘 지우지 않으셨군요....

![image](https://github.com/Dev-FE-1/idle-intranet-service/assets/89791868/a746e96c-66f3-4cb7-8cd7-ab2698ea05d5)

2024-06-26 00:10 UTC, devdeun commented
아이콘 파일 삭제했습니다 ㅎㅎㅎ
menus 배열도 Route 컴포넌트에서 관리하는게 좋을 것 같아서 해당 작업도 같이 했어요!

2024-06-26 00:43 UTC, seoyoonyi approved these changes

2024-06-26 02:15 UTC, HSjjs98 approved these changes

2024-06-26 02:15 UTC, merged